### ISSUE TITLE
Add an independent scroll for both columns.

### ISSUE THREAD

**Issue by givek** [rsbear/nvimluau#32]
First of all, kudos! 

However, while using the website, I noticed that both columns scrolled at the same time. I think this could be improved by giving both columns their own independent scroll. Should I try to implement something similar? Or is this the desired behaviour?

**Comment by rsbear** [comment]
I love this idea and completely agree that both columns should scroll independently. I have plans to do a couple of improvements before implementing. If you'd like to give it a shot and would have fun doing so, you're more than welcome to!

**Comment by givek** [comment]
I'm glad you liked the concept. I'll try to put it into action and give it a shot.

**Comment by givek** [comment]
@rsbear, should I submit the pull request to the main branch?

**Comment by rsbear** [comment]
A feature branch if you don't mind!
